version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nestjs_mysql_db
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: nestjs_tutorial
      MYSQL_USER: tutorial_user
      MYSQL_PASSWORD: tutorial_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3308:3306"
